GET http://localhost:80/api/item?id=99
Accept: application/json

###

POST https://localhost:8006/api/v1/migration/anonymous/validateBrs
Content-Type: application/json

{
  "registrationNumber": "1232435",
  "directorIdNumber": "12345556"
}

###
POST https://localhost:8006/api/v1/migration/anonymous/validateToken
Content-Type: application/json

{
  "phone": "254723703068",
  "token": "70A505E8"
}
