insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('COUNTIES_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('COUNTIES_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('COUNTIES_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DEPARTMENTS_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DEPARTMENTS_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DEPARTMENTS_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DESIGNATIONS_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DESIGNATIONS_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DESIGNATIONS_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DIRECTORATES_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DIRECTORATES_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DIRECTORATES_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DIVISIONS_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DIVISIONS_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('DIVISIONS_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('REGIONS_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('REGIONS_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('REGIONS_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SUB_REGIONS_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SUB_REGIONS_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SUB_REGIONS_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SECTIONS_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SECTIONS_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SECTIONS_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SUBSECTIONS_L1_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SUBSECTIONS_L1_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SUBSECTIONS_L1_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SUBSECTIONS_L2_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SUBSECTIONS_L2_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SUBSECTIONS_L2_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('TOWNS_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('TOWNS_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('TOWNS_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('AUTHORITIES_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('AUTHORITY_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('AUTHORITY_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('RBAC_ASSIGN_AUTHORIZATION', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('RBAC_ASSIGN_ROLE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('RBAC_REVOKE_AUTHORIZATION', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('RBAC_REVOKE_ROLE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('RBAC_ROLE_AUTHORITIES_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('RBAC_ROLE_AUTHORITIES_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('RBAC_USER_ROLES_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('ROLES_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('ROLES_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('ROLES_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('TITLES_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('TITLES_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('TITLES_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('USERS_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('USERS_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('USERS_WRITE', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('SYSADMIN_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('USER_TYPES_LIST', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('USER_TYPES_VIEW', 1);
insert into CFG_USER_PRIVILEGES (NAME, STATUS)
VALUES ('USER_TYPES_WRITE', 1);
commit;


insert into CFG_ROLES_PRIVILEGES (ROLES_ID, PRIVILEGE_ID, STATUS)
select 40, ID, 1
from CFG_USER_PRIVILEGES
where NAME in ('AUTHORITY_LIST')
;

select *
from CFG_USER_PRIVILEGES
where NAME = 'COUNTIES_LIST';

select *
from DAT_KEBS_USERS
where USER_NAME = 'vmuriuki';

select *
from CFG_USER_ROLES_ASSIGNMENTS
where USER_ID = 54;


insert into CFG_ROLES_PRIVILEGES (ROLES_ID, PRIVILEGE_ID, STATUS)
select 40, ID, 1
from CFG_USER_PRIVILEGES
where ID in (
    select ID
    from CFG_USER_PRIVILEGES
    where id >= 683
    minus
    select PRIVILEGE_ID
    from CFG_ROLES_PRIVILEGES
    where ROLES_ID = 40
)
;

commit;
