SELECT * FROM DAT_KEBS_QA_INVOICE_MASTER_DETAILS WHERE PERMIT_REF_NUMBER =:permitRefNumber;
SELECT ITEM_DESC_NAME, ITEM_QUANTITY,ITEM_AMOUNT,PERMIT_STATUS FROM APOLLO.DAT_KEBS_QA_INVOICE_DETAILS a
JOIN APOLLO.DAT_KEBS_QA_INVOICE_MASTER_DETAILS b ON a.INVOICE_MASTER_ID = b.ID
WHERE b.PERMIT_REF_NUMBER =;

SELECT DISTINCT pr.* FROM DAT_KEBS_PERMIT_TRANSACTION pr, DAT_KEBS_MANUFACTURE_PLANT_DETAILS B WHERE pr.ATTACHED_PLANT_ID = B.ID AND pr.PERMIT_AWARD_STATUS IS NULL
AND pr.PAID_STATUS = :paidStatus AND pr.PERMIT_TYPE = :permitType
AND pr.SECTION_ID = :sectionID AND B.REGION = :region
ORDER BY pr.ID DESC FETCH FIRST 20 ROWS ONLY;

SELECT * FROM DAT_KEBS_MANUFACTURE_PLANT_DETAILS a
JOIN DAT_KEBS_COMPANY_PROFILE b on a.MANUFACTURE_ID = a.ID
         WHERE b.FIRM_CATEGORY = 3 AND a.INVOICE_INSPECTION_GENERATED = 1 AND a.INSPECTION_FEE_STATUS = 1
                CURRENT_DATE > a.PAID_DATE  AND CURRENT_DATE < a.ENDING_DATE ;

'308013-00', '308033-00', '308034-00', '308034-02' ,'308034-03' ,'308035-00', '308035-02', '308035-03', '309446-00' ,'309449-00', '309449-02' ,'309449-03' ,'307995-00'
