
###
GET https://localhost:8006/api/v1/migration/anonymous/titles/

###
GET https://localhost:8006/api/v1/migration/secure/user/details/2046
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJJYW5fS2lwcm9ubyIsImlzcyI6ImtpbXMua2Vicy5vcmciLCJpYXQiOjE2MjkzNzcwNzcsImV4cCI6MTYyOTM4MzA3NywiYWRkcmVzcyI6IjEyNy4wLjAuMSIsInVzZXJBZ2VudCI6IltBcGFjaGUtSHR0cENsaWVudC80LjUuMTIgKEphdmEvMTEuMC4xMCldIiwiZnVsbE5hbWUiOiJJYW4gS2lwcm9ubyIsInJvbGVzIjoiUEVSTUlUX0FQUExJQ0FUSU9OLFBFUk1JVF9SRU5FV0FMLFBWT0NfQVBQTElDQVRJT05fUkVBRCxMSVNUX0NPTVBBTlksTU9ESUZZX0NPTVBBTlkifQ.T6rnoVjZ0kkIKUa_th1YYQKLFgxVw0O7dbkElm_7yJTCrPIzSEOt4Tj40eIa45VvdkBaUK7o13MKGp9nub_eUg

###
POST https://127.0.0.1:8006/api/v1/login
Content-Type: application/json

{
  "username": "Ian_Kiprono",
  "password": "password"}

> {%
    client.global.set("auth_token", response.headers.valuesOf('accessToken')[0]);
%}


###GET Department
GET https://localhost:8006/api/v1/migration/anonymous/standard/dropdown/getDepartments


###GET Department
POST https://localhost:8006/api/v1/migration/anonymous/standard/deploy

###GET Department
GET https://localhost:8006/api/v1/migration/standard/getHOFTasks
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJJYW5fS2lwcm9ubyIsImlzcyI6ImtpbXMua2Vicy5vcmciLCJpYXQiOjE2MzA2ODQ4OTMsImV4cCI6MTYzMDY5MDg5MywiYWRkcmVzcyI6IjEyNy4wLjAuMSIsInVzZXJBZ2VudCI6IltBcGFjaGUtSHR0cENsaWVudC80LjUuMTIgKEphdmEvMTEuMC4xMCldIiwiZnVsbE5hbWUiOiJJYW4gS2lwcm9ubyIsInJvbGVzIjoiUEVSTUlUX0FQUExJQ0FUSU9OLFBFUk1JVF9SRU5FV0FMLFBWT0NfQVBQTElDQVRJT05fUkVBRCxMSVNUX0NPTVBBTlksTU9ESUZZX0NPTVBBTlkifQ.-wkcNvpsY690_1HKlbjdJ1eyKe0w6OQs-Ea-fA4vWtcOq5vj8abTCr8LGxp_WLEYRr5DowlgzghYqK6sgRLC3w


#### Table to search for process instance id is ACT_HI_ACTINST
POST https://localhost:8006/api/v1/migration/anonymous/standard/close
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJJYW5fS2lwcm9ubyIsImlzcyI6ImtpbXMua2Vicy5vcmciLCJpYXQiOjE2MzA2ODQ4OTMsImV4cCI6MTYzMDY5MDg5MywiYWRkcmVzcyI6IjEyNy4wLjAuMSIsInVzZXJBZ2VudCI6IltBcGFjaGUtSHR0cENsaWVudC80LjUuMTIgKEphdmEvMTEuMC4xMCldIiwiZnVsbE5hbWUiOiJJYW4gS2lwcm9ubyIsInJvbGVzIjoiUEVSTUlUX0FQUExJQ0FUSU9OLFBFUk1JVF9SRU5FV0FMLFBWT0NfQVBQTElDQVRJT05fUkVBRCxMSVNUX0NPTVBBTlksTU9ESUZZX0NPTVBBTlkifQ.-wkcNvpsY690_1HKlbjdJ1eyKe0w6OQs-Ea-fA4vWtcOq5vj8abTCr8LGxp_WLEYRr5DowlgzghYqK6sgRLC3w
Content-Type: application/json

{
  "message": "d5713c4a-ad7c-11eb-b912-fe5c68490b49"


}



####
POST https://localhost:8006/api/v1/migration/standard/process
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJJYW5fS2lwcm9ubyIsImlzcyI6ImtpbXMua2Vicy5vcmciLCJpYXQiOjE2MzA2Nzc5ODYsImV4cCI6MTYzMDY4Mzk4NiwiYWRkcmVzcyI6IjEyNy4wLjAuMSIsInVzZXJBZ2VudCI6IltBcGFjaGUtSHR0cENsaWVudC80LjUuMTIgKEphdmEvMTEuMC4xMCldIiwiZnVsbE5hbWUiOiJJYW4gS2lwcm9ubyIsInJvbGVzIjoiUEVSTUlUX0FQUExJQ0FUSU9OLFBFUk1JVF9SRU5FV0FMLFBWT0NfQVBQTElDQVRJT05fUkVBRCxMSVNUX0NPTVBBTlksTU9ESUZZX0NPTVBBTlkifQ.K6bsVoFLsbBghVzzreoFTMOr6kvqBL5Jxrtii4nXmqKGCwGr_GmCndqvf5e6WfLg5824ngy_H7oztnrYV4rwZA
Content-Type: application/json

{
  "id": "86be9122-9dd6-11eb-bd98-2c337a287f07"


}
