
###
POST https://localhost:8006/api/v1/login/b
Content-Type: application/json

{
  "username": "qaogarissa@mail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", response.headers.valuesOf('accessToken')[0]);
%}
###

####
GET https://localhost:8006/api/v1/migration/qa/permit/awarded-list-completely?permitTypeID=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXRlQG1haWwuY29tIiwiaXNzIjoia2ltcy5rZWJzLm9yZyIsImlhdCI6MTY1MjI1MTU3NSwiZXhwIjoxNjUyMjU3NTc1LCJhZGRyZXNzIjoiMTI3LjAuMC4xIiwidXNlckFnZW50IjoiW0FwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMiAoSmF2YS8xMS4wLjEwKV0iLCJmdWxsTmFtZSI6IkthdGUgVGVzdCIsInJvbGVzIjoiVVNFUixQRVJNSVRfQVBQTElDQVRJT04sUEVSTUlUX1JFTkVXQUwsUFZPQ19BUFBMSUNBVElPTl9SRUFELExJU1RfQ09NUEFOWSxNT0RJRllfQ09NUEFOWSxTTF9TSVRFX1ZJU0lUX0ZFRURCQUNLX1ZJRVcsU0xfU0xJX0ZPUk1fQ1JFQVRFLFNMX1NMSV9DX0ZPUk1fQ1JFQVRFLFNMX1NMSV9DX0ZPUk1fVklFVyxTTF9TTElfRk9STV9WSUVXIn0.OmtKD7H6gfkD3AgdWkihEE4-VwF4H6tuFGjBgOlfMhNmMWidscg_UtmDsarR1iVVlHrD3dB9pk3NOtx3ARWUdQ

###
GET https://localhost:8006/api/v1/migration/qa/payments
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxYW1nYXJpc3NhQG1haWwuY29tIiwiaXNzIjoia2ltcy5rZWJzLm9yZyIsImlhdCI6MTY2NTU4NzExMSwiZXhwIjoxNjY1NTkzMTExLCJhZGRyZXNzIjoiMTI3LjAuMC4xIiwidXNlckFnZW50IjoiW0FwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMyAoSmF2YS8xNy4wLjQuMSldIiwiZnVsbE5hbWUiOiJRQU0gR2FyaXNzYSIsInJvbGVzIjoiVVNFUixFTVBMT1lFRSxRQV9QU0NfTUVNQkVSU19SRUFELFFBX1BTQ19NRU1CRVJTX01PRElGWSxRQV9NQU5BR0VSX1JFQUQsUUFfTUFOQUdFUl9NT0RJRlksUUFfUENNX01PRElGWSxRQV9QQ01fUkVBRCJ9.dZEFyvnG1BuZt0Sy4zXEqmu8qMkycTBETG2FkqFzE__x2qIHS2TjE-juvxZRzJ-xZBYyWG_FOuihCfEPfbFs_w

###
GET https://localhost:8006/api/v1/migration/qa/permit/reports/allSmarkPermits
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxYW1nYXJpc3NhQG1haWwuY29tIiwiaXNzIjoia2ltcy5rZWJzLm9yZyIsImlhdCI6MTY2NTU4NzExMSwiZXhwIjoxNjY1NTkzMTExLCJhZGRyZXNzIjoiMTI3LjAuMC4xIiwidXNlckFnZW50IjoiW0FwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMyAoSmF2YS8xNy4wLjQuMSldIiwiZnVsbE5hbWUiOiJRQU0gR2FyaXNzYSIsInJvbGVzIjoiVVNFUixFTVBMT1lFRSxRQV9QU0NfTUVNQkVSU19SRUFELFFBX1BTQ19NRU1CRVJTX01PRElGWSxRQV9NQU5BR0VSX1JFQUQsUUFfTUFOQUdFUl9NT0RJRlksUUFfUENNX01PRElGWSxRQV9QQ01fUkVBRCJ9.dZEFyvnG1BuZt0Sy4zXEqmu8qMkycTBETG2FkqFzE__x2qIHS2TjE-juvxZRzJ-xZBYyWG_FOuihCfEPfbFs_w


###
GET https://localhost:8006/api/v1/migration/qa/permit/reports/allPermitsWithNoFmarkGenerated?permitTypeID=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxYW1nYXJpc3NhQG1haWwuY29tIiwiaXNzIjoia2ltcy5rZWJzLm9yZyIsImlhdCI6MTY2NTczODM2OCwiZXhwIjoxNjY1NzQ0MzY4LCJhZGRyZXNzIjoiMTI3LjAuMC4xIiwidXNlckFnZW50IjoiW0FwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMyAoSmF2YS8xNy4wLjQuMSldIiwiZnVsbE5hbWUiOiJRQU0gR2FyaXNzYSIsInJvbGVzIjoiVVNFUixFTVBMT1lFRSxRQV9QU0NfTUVNQkVSU19SRUFELFFBX1BTQ19NRU1CRVJTX01PRElGWSxRQV9NQU5BR0VSX1JFQUQsUUFfTUFOQUdFUl9NT0RJRlksUUFfUENNX01PRElGWSxRQV9QQ01fUkVBRCJ9.UxWVz7yFam0b6NDisX5oKuzlCIIJe1-DVgGIFZKTq14ezV7v666Pk6W2AS5B6zjuS6WmOejQ4yMYxB9r1icZYQ
