
###
POST https://localhost:8006/api/v1/login/b
Content-Type: application/json

{
  "username": "kate@mail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", response.headers.valuesOf('accessToken')[0]);
%}
###

####
GET https://localhost:8006/api/v1/migration/qa/permit/awarded-list-completely?permitTypeID=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXRlQG1haWwuY29tIiwiaXNzIjoia2ltcy5rZWJzLm9yZyIsImlhdCI6MTY1MjI1MTU3NSwiZXhwIjoxNjUyMjU3NTc1LCJhZGRyZXNzIjoiMTI3LjAuMC4xIiwidXNlckFnZW50IjoiW0FwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMiAoSmF2YS8xMS4wLjEwKV0iLCJmdWxsTmFtZSI6IkthdGUgVGVzdCIsInJvbGVzIjoiVVNFUixQRVJNSVRfQVBQTElDQVRJT04sUEVSTUlUX1JFTkVXQUwsUFZPQ19BUFBMSUNBVElPTl9SRUFELExJU1RfQ09NUEFOWSxNT0RJRllfQ09NUEFOWSxTTF9TSVRFX1ZJU0lUX0ZFRURCQUNLX1ZJRVcsU0xfU0xJX0ZPUk1fQ1JFQVRFLFNMX1NMSV9DX0ZPUk1fQ1JFQVRFLFNMX1NMSV9DX0ZPUk1fVklFVyxTTF9TTElfRk9STV9WSUVXIn0.OmtKD7H6gfkD3AgdWkihEE4-VwF4H6tuFGjBgOlfMhNmMWidscg_UtmDsarR1iVVlHrD3dB9pk3NOtx3ARWUdQ

####
GET https://localhost:8006/api/v1/migration/qa/payments
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrYXRlQG1haWwuY29tIiwiaXNzIjoia2ltcy5rZWJzLm9yZyIsImlhdCI6MTY1MjI2NzA3OSwiZXhwIjoxNjUyMjczMDc5LCJhZGRyZXNzIjoiMTI3LjAuMC4xIiwidXNlckFnZW50IjoiW0FwYWNoZS1IdHRwQ2xpZW50LzQuNS4xMiAoSmF2YS8xMS4wLjEwKV0iLCJmdWxsTmFtZSI6IkthdGUgVGVzdCIsInJvbGVzIjoiVVNFUixQRVJNSVRfQVBQTElDQVRJT04sUEVSTUlUX1JFTkVXQUwsUFZPQ19BUFBMSUNBVElPTl9SRUFELExJU1RfQ09NUEFOWSxNT0RJRllfQ09NUEFOWSxTTF9TSVRFX1ZJU0lUX0ZFRURCQUNLX1ZJRVcsU0xfU0xJX0ZPUk1fQ1JFQVRFLFNMX1NMSV9DX0ZPUk1fQ1JFQVRFLFNMX1NMSV9DX0ZPUk1fVklFVyxTTF9TTElfRk9STV9WSUVXIn0.6oLxnIgCsCmgsackImf1b3x5B6N6AmzQR9fKRsaK9R-RygFktMXZX5iu5JzBcsMt7Q5UR-67FHkix0Q2fZmliw
