POST http://localhost:8080/publicreview/deploy_publicreview


###
POST http://localhost:8080/publicreview/preparepr
Content-Type: application/json

{
  "prdName": "3242WE",
  "prdraftBy": "TC_SEC",
  "prdpath": "http://localhost:8080/files/CommitteeStage.docx"
}


#####
GET http://localhost:8080/publicreview/getprs

#####
GET http://localhost:8080/publicreview/publicreviewdraft/1


###
POST http://localhost:8080/publicreview/commentpr
Content-Type: application/json

{
  "prdId": "1",
  "roleId": "2",
  "roleName": "number",
  "userId": "2",
  "title": "number",
  "documentType": "number",
  "circulationDate": "number",
  "closingDate": "number",
  "organization": "number",
  "clause": "number",
  "commentType": "number",
  "comment": "number",
  "proposedChange": "number",
  "observations": "number"
}

#####
GET http://localhost:8080/publicreview/getprcomments




