//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.20 at 04:35:28 AM EAT 
//
package com.example.kraPinValidations.kraPinIntegrations

import org.kebs.app.kotlin.apollo.api.objects.integ.kra.soap.kraPinIntegrations.*
import javax.xml.bind.JAXBElement
import javax.xml.bind.annotation.XmlElementDecl
import javax.xml.bind.annotation.XmlRegistry
import javax.xml.namespace.QName

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.example.kraPinValidations.kraPinIntegrations package.
 *
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
class ObjectFactory
/**
 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.kraPinValidations.kraPinIntegrations
 *
 */
{
    /**
     * Create an instance of [ReceiveApprovedExmpDAFPDtls]
     *
     */
    fun createReceiveApprovedExmpDAFPDtls(): ReceiveApprovedExmpDAFPDtls {
        return ReceiveApprovedExmpDAFPDtls()
    }

    /**
     * Create an instance of [ReceiveApprovedExmpDAFPDtlsResponse]
     *
     */
    fun createReceiveApprovedExmpDAFPDtlsResponse(): ReceiveApprovedExmpDAFPDtlsResponse {
        return ReceiveApprovedExmpDAFPDtlsResponse()
    }

    /**
     * Create an instance of [ReceiveApprovedExmpOAFPDtls]
     *
     */
    fun createReceiveApprovedExmpOAFPDtls(): ReceiveApprovedExmpOAFPDtls {
        return ReceiveApprovedExmpOAFPDtls()
    }

    /**
     * Create an instance of [ReceiveApprovedExmpOAFPDtlsResponse]
     *
     */
    fun createReceiveApprovedExmpOAFPDtlsResponse(): ReceiveApprovedExmpOAFPDtlsResponse {
        return ReceiveApprovedExmpOAFPDtlsResponse()
    }

    /**
     * Create an instance of [ReceiveOAFPMstDtls]
     *
     */
    fun createReceiveOAFPMstDtls(): ReceiveOAFPMstDtls {
        return ReceiveOAFPMstDtls()
    }

    /**
     * Create an instance of [ReceiveOAFPMstDtlsResponse]
     *
     */
    fun createReceiveOAFPMstDtlsResponse(): ReceiveOAFPMstDtlsResponse {
        return ReceiveOAFPMstDtlsResponse()
    }

    /**
     * Create an instance of [ValidatePIN]
     *
     */
    fun createValidatePIN(): ValidatePIN {
        return ValidatePIN()
    }

    /**
     * Create an instance of [ValidatePINResponse]
     *
     */
    fun createValidatePINResponse(): ValidatePINResponse {
        return ValidatePINResponse()
    }

    /**
     * Create an instance of [JAXBElement]`<`[ReceiveApprovedExmpDAFPDtls]`>`
     *
     * @param value
     * Java instance representing xml element's value.
     * @return
     * the new instance of [JAXBElement]`<`[ReceiveApprovedExmpDAFPDtls]`>`
     */
    @XmlElementDecl(namespace = "http://impl.external.intf.kra.tcs.com/", name = "receiveApprovedExmpDAFPDtls")
    fun createReceiveApprovedExmpDAFPDtls(value: ReceiveApprovedExmpDAFPDtls): JAXBElement<ReceiveApprovedExmpDAFPDtls> {
        return JAXBElement<ReceiveApprovedExmpDAFPDtls>(
            _ReceiveApprovedExmpDAFPDtls_QNAME,
            ReceiveApprovedExmpDAFPDtls::class.java,
            null,
            value
        )
    }

    /**
     * Create an instance of [JAXBElement]`<`[ReceiveApprovedExmpDAFPDtlsResponse]`>`
     *
     * @param value
     * Java instance representing xml element's value.
     * @return
     * the new instance of [JAXBElement]`<`[ReceiveApprovedExmpDAFPDtlsResponse]`>`
     */
    @XmlElementDecl(namespace = "http://impl.external.intf.kra.tcs.com/", name = "receiveApprovedExmpDAFPDtlsResponse")
    fun createReceiveApprovedExmpDAFPDtlsResponse(value: ReceiveApprovedExmpDAFPDtlsResponse): JAXBElement<ReceiveApprovedExmpDAFPDtlsResponse> {
        return JAXBElement<ReceiveApprovedExmpDAFPDtlsResponse>(
            _ReceiveApprovedExmpDAFPDtlsResponse_QNAME,
            ReceiveApprovedExmpDAFPDtlsResponse::class.java,
            null,
            value
        )
    }

    /**
     * Create an instance of [JAXBElement]`<`[ReceiveApprovedExmpOAFPDtls]`>`
     *
     * @param value
     * Java instance representing xml element's value.
     * @return
     * the new instance of [JAXBElement]`<`[ReceiveApprovedExmpOAFPDtls]`>`
     */
    @XmlElementDecl(namespace = "http://impl.external.intf.kra.tcs.com/", name = "receiveApprovedExmpOAFPDtls")
    fun createReceiveApprovedExmpOAFPDtls(value: ReceiveApprovedExmpOAFPDtls): JAXBElement<ReceiveApprovedExmpOAFPDtls> {
        return JAXBElement<ReceiveApprovedExmpOAFPDtls>(
            _ReceiveApprovedExmpOAFPDtls_QNAME,
            ReceiveApprovedExmpOAFPDtls::class.java,
            null,
            value
        )
    }

    /**
     * Create an instance of [JAXBElement]`<`[ReceiveApprovedExmpOAFPDtlsResponse]`>`
     *
     * @param value
     * Java instance representing xml element's value.
     * @return
     * the new instance of [JAXBElement]`<`[ReceiveApprovedExmpOAFPDtlsResponse]`>`
     */
    @XmlElementDecl(namespace = "http://impl.external.intf.kra.tcs.com/", name = "receiveApprovedExmpOAFPDtlsResponse")
    fun createReceiveApprovedExmpOAFPDtlsResponse(value: ReceiveApprovedExmpOAFPDtlsResponse): JAXBElement<ReceiveApprovedExmpOAFPDtlsResponse> {
        return JAXBElement<ReceiveApprovedExmpOAFPDtlsResponse>(
            _ReceiveApprovedExmpOAFPDtlsResponse_QNAME,
            ReceiveApprovedExmpOAFPDtlsResponse::class.java,
            null,
            value
        )
    }

    /**
     * Create an instance of [JAXBElement]`<`[ReceiveOAFPMstDtls]`>`
     *
     * @param value
     * Java instance representing xml element's value.
     * @return
     * the new instance of [JAXBElement]`<`[ReceiveOAFPMstDtls]`>`
     */
    @XmlElementDecl(namespace = "http://impl.external.intf.kra.tcs.com/", name = "receiveOAFPMstDtls")
    fun createReceiveOAFPMstDtls(value: ReceiveOAFPMstDtls): JAXBElement<ReceiveOAFPMstDtls> {
        return JAXBElement<ReceiveOAFPMstDtls>(_ReceiveOAFPMstDtls_QNAME, ReceiveOAFPMstDtls::class.java, null, value)
    }

    /**
     * Create an instance of [JAXBElement]`<`[ReceiveOAFPMstDtlsResponse]`>`
     *
     * @param value
     * Java instance representing xml element's value.
     * @return
     * the new instance of [JAXBElement]`<`[ReceiveOAFPMstDtlsResponse]`>`
     */
    @XmlElementDecl(namespace = "http://impl.external.intf.kra.tcs.com/", name = "receiveOAFPMstDtlsResponse")
    fun createReceiveOAFPMstDtlsResponse(value: ReceiveOAFPMstDtlsResponse): JAXBElement<ReceiveOAFPMstDtlsResponse> {
        return JAXBElement<ReceiveOAFPMstDtlsResponse>(
            _ReceiveOAFPMstDtlsResponse_QNAME,
            ReceiveOAFPMstDtlsResponse::class.java,
            null,
            value
        )
    }

    /**
     * Create an instance of [JAXBElement]`<`[ValidatePIN]`>`
     *
     * @param value
     * Java instance representing xml element's value.
     * @return
     * the new instance of [JAXBElement]`<`[ValidatePIN]`>`
     */
    @XmlElementDecl(namespace = "http://impl.external.intf.kra.tcs.com/", name = "validatePIN")
    fun createValidatePIN(value: ValidatePIN): JAXBElement<ValidatePIN> {
        return JAXBElement<ValidatePIN>(_ValidatePIN_QNAME, ValidatePIN::class.java, null, value)
    }

    /**
     * Create an instance of [JAXBElement]`<`[ValidatePINResponse]`>`
     *
     * @param value
     * Java instance representing xml element's value.
     * @return
     * the new instance of [JAXBElement]`<`[ValidatePINResponse]`>`
     */
    @XmlElementDecl(namespace = "http://impl.external.intf.kra.tcs.com/", name = "validatePINResponse")
    fun createValidatePINResponse(value: ValidatePINResponse): JAXBElement<ValidatePINResponse> {
        return JAXBElement<ValidatePINResponse>(
            _ValidatePINResponse_QNAME,
            ValidatePINResponse::class.java,
            null,
            value
        )
    }

    companion object {
        private val _ReceiveApprovedExmpDAFPDtls_QNAME =
            QName("http://impl.external.intf.kra.tcs.com/", "receiveApprovedExmpDAFPDtls")
        private val _ReceiveApprovedExmpDAFPDtlsResponse_QNAME =
            QName("http://impl.external.intf.kra.tcs.com/", "receiveApprovedExmpDAFPDtlsResponse")
        private val _ReceiveApprovedExmpOAFPDtls_QNAME =
            QName("http://impl.external.intf.kra.tcs.com/", "receiveApprovedExmpOAFPDtls")
        private val _ReceiveApprovedExmpOAFPDtlsResponse_QNAME =
            QName("http://impl.external.intf.kra.tcs.com/", "receiveApprovedExmpOAFPDtlsResponse")
        private val _ReceiveOAFPMstDtls_QNAME = QName("http://impl.external.intf.kra.tcs.com/", "receiveOAFPMstDtls")
        private val _ReceiveOAFPMstDtlsResponse_QNAME =
            QName("http://impl.external.intf.kra.tcs.com/", "receiveOAFPMstDtlsResponse")
        private val _ValidatePIN_QNAME = QName("http://impl.external.intf.kra.tcs.com/", "validatePIN")
        private val _ValidatePINResponse_QNAME = QName("http://impl.external.intf.kra.tcs.com/", "validatePINResponse")
    }
}