###REQUEST FOR STANDARD ENDPOINTS ######

###POST deploy application
POST http://localhost:8080/standard/deploy

###POST apply for standard request
POST http://localhost:8080/standard/request
Content-Type: application/json

{
  "requestNumber": "ENG/02:2021",
  "requestor_id": {"id": "1","name": "Stephen Caleb","phone": "0725811052","email": "smuganda@gmail.com"},
  "tc_id": "1",
  "department_id": "1",
  "product_category": "1"
}

###GET all tasks assigned to a HOF
GET http://localhost:8080/standard/getHOFTasks

###POST Complete review by HOF
POST http://localhost:8080/standard/hof/review
Content-Type: application/json

{
  "id": "c58c2a70-a50c-11eb-9235-28b2bd7bef93"
}

###GET all tasks assigned to a TC-SEC
GET http://localhost:8080/standard/getTCSECTasks

###POST apply for standard request
POST http://localhost:8080/standard/uploadNWI
Content-Type: application/json

{
  "proposal_title": "ENG/01:2021",
  "name_of_proposer": "Edwin Inganji",
  "taskId": "eb4d67bc-a6b2-11eb-9235-28b2bd7bef93"
}

###GET all tasks assigned to a TC
GET http://localhost:8080/standard/getTCTasks

### POST Provide decision on NWI
POST http://localhost:8080/standard/decisionOnNWI
Content-Type: application/json

{
  "taskId": "76ccd9f4-a35b-11eb-8f9a-fe5c68490b49",
  "decision": "true"
}

###GET all tasks assigned to a TC
GET http://localhost:8080/standard/tc-sec/tasks


###POST upload justification
POST http://localhost:8080/standard/uploadJustification
Content-Type: application/json

{
  "title": "ENG/01:2021",
  "scope": "scope",
  "purpose": "purpose",
  "taskId": "9500f00b-a35b-11eb-8f9a-fe5c68490b49"
}


###GET all tasks assigned to a SPC-Sec for justification
GET http://localhost:8080/standard/spc-sec/tasks

### POST Provide decision on Justification
POST http://localhost:8080/standard/decisionOnJustification
Content-Type: application/json

{
  "taskId": "a68d4721-a35b-11eb-8f9a-fe5c68490b49",
  "decision": "true"
}

###GET all tasks assigned to a TC for the workplan
GET http://localhost:8080/standard/tc-sec/tasks/workplan

###POST upload workplan
POST http://localhost:8080/standard/uploadWorkPlan
Content-Type: application/json

{
  "title": "ENG/01:2021",
  "taskId": "b3326e18-a35b-11eb-8f9a-fe5c68490b49"
}

###GET Department
GET http://localhost:8080/standard/getDepartments

###GET technical committee
GET http://localhost:8080/standard/getTechnicalCommittee

###GET products
GET http://localhost:8080/standard/getProducts

###GET product categories
GET http://localhost:8080/standard/getProductCategories/1

###POST Product categories
POST http://localhost:8080/standard/getProductCategories
Content-Type: application/json

{
  "id": "1"
}



###POST process state
POST http://localhost:8080/standard/process
Content-Type: application/json

{
  "id": "46ae472c-a35b-11eb-8f9a-fe5c68490b49"
}

###

######################################################PUBLISHING ENDPOINTS #####################################################

###POST deploy application
POST http://localhost:8080/publishing/deploy

###POST submit draft standard
POST http://localhost:8080/publishing/submit
Content-Type: application/json

{
  "title": "ENG/01:2021",
  "requestor_id": "1",
  "standard_officer_id": "1"
}

###
###GET all tasks assigned to a HOP
GET http://localhost:8080/publishing/getHOPTasks

### POST Provide decision on KS draft
POST http://localhost:8080/publishing/decisionOnKSDraft
Content-Type: application/json

{
  "taskId": "d352d544-a669-11eb-b7e6-fe5c68490b49",
  "decision": "true"
}


###POST upload rejection feedback
POST http://localhost:8080/publishing/uploadRejectionFeedback
Content-Type: application/json

{
  "item_id": "ENG/01:2021",
  "user_id": "1",
  "status": "false",
  "comment": "Its not upto standard",
  "taskId": "5f6f6020-a3fd-11eb-b2bd-fe5c68490b49"
}


###GET all tasks assigned to Editors
GET http://localhost:8080/publishing/getEditorTasks

###POST finished editing draft
POST http://localhost:8080/publishing/finishEditingDraft
Content-Type: application/json

{
  "title": "ENG/01:2021",
  "requestor_id": "1",
  "standard_officer_id": "1",
  "version_number": "1",
  "taskId": "e13cb13d-a669-11eb-b7e6-fe5c68490b49"
}

###GET all tasks assigned to Proofreader
GET http://localhost:8080/publishing/getProofReaderTasks


### POST Provide decision on KS draft
POST http://localhost:8080/publishing/finishedProofReading
Content-Type: application/json

{
  "taskId": "fe796f03-a669-11eb-b7e6-fe5c68490b49",
  "decision": "true"
}



###GET all tasks assigned to a Draughtsman
GET http://localhost:8080/publishing/getDraughtsmanTasks

###POST finished draughting
POST http://localhost:8080/publishing/uploadDraughtChanges
Content-Type: application/json

{
  "title": "ENG/01:2021",
  "requestor_id": "1",
  "standard_officer_id": "1",
  "version_number": "2",
  "taskId": "0effa0bc-a66a-11eb-b7e6-fe5c68490b49"
}

###GET all tasks assigned to a HOP
GET http://localhost:8080/publishing/getHOPTasks

###POST approve draft standard change
POST http://localhost:8080/publishing/approvedDraftStandard
Content-Type: application/json

{
  "title": "ENG/01:2021",
  "requestor_id": "1",
  "taskId": "3089bfa0-a66a-11eb-b7e6-fe5c68490b49"
}



###

