###POST deploy application
POST http://localhost:8080/standard/deploy

###POST apply for standard request
POST http://localhost:8080/standard/request
Content-Type: application/json

{
  "requestNumber": "ENG/01:2021",
  "requestor_id": {"id": "1","name": "Edwin Inganji","phone": "0700402788","email": "einganji@gmail.com"},
  "tc_id": "1",
  "department_id": "1",
  "product_category": "1"
}

###GET all tasks assigned to a HOF
GET http://localhost:8080/standard/getHOFTasks

###GET Complete review by HOF
GET http://localhost:8080/standard/hof/review/86af0467-9e93-11eb-bcc5-2c337a287f07

###GET all tasks assigned to a TC-SEC
GET http://localhost:8080/standard/getTCSECTasks

###POST apply for standard request
POST http://localhost:8080/standard/uploadNWI/faf25a81-9e93-11eb-bcc5-2c337a287f07
Content-Type: application/json

{
  "proposal_title": "ENG/01:2021",
  "name_of_proposer": "Edwin Inganji"
}

###GET all tasks assigned to a TC
GET http://localhost:8080/standard/getTCTasks

### POST Provide decision on NWI
POST http://localhost:8080/standard/decisionOnNWI/2f29a9c7-9e94-11eb-bcc5-2c337a287f07/true

###GET all tasks assigned to a TC
GET http://localhost:8080/standard/tc-sec/tasks


###POST upload justification
POST http://localhost:8080/standard/uploadJustification/67d1999e-9e94-11eb-bcc5-2c337a287f07
Content-Type: application/json

{
  "title": "ENG/01:2021",
  "scope": "scope",
  "purpose": "purpose"
}


###GET all tasks assigned to a SPC-Sec for justification
GET http://localhost:8080/standard/spc-sec/tasks

### POST Provide decision on Justification
POST http://localhost:8080/standard/decisionOnJustification/7ffac014-9e94-11eb-bcc5-2c337a287f07/true

###GET all tasks assigned to a TC for the workplan
GET http://localhost:8080/standard/tc-sec/tasks/workplan

###POST upload workplan
POST http://localhost:8080/standard/uploadWorkPlan/94169bab-9e94-11eb-bcc5-2c337a287f07
Content-Type: application/json

{
  "title": "ENG/01:2021"
}


###GET products
GET http://localhost:8080/standard/getProducts

###GET process state
GET http://localhost:8080/standard/process/7fe5cdcf-9e93-11eb-bcc5-2c337a287f07

###


